inherit: 
    - models/small.yaml
    - wandb.yaml

model:
    n_dims: 21
    n_positions: 101

training:
    task: decision_tree_and_linear_with_labels
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 1000001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 26
            end: 101
            inc: 5
            interval: 2000

out_dir: ../models/decision_tree_and_linear_with_labels

wandb:
    name: "decision_tree_and_linear_with_labels"
